name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: RayXu6/mcsrcndoc
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: chmod -R a+x node_modules && git init && npm run gh:build
          BUILD_DIR: docs/.vuepress/dist/