name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: RayXu6/mcsrcndoc
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: chmod -R a+x node_modules && npm run gh:build && cd /docs/.vuepress/dist/.git/ && git config --global user.name RayXu6 && git config --global user.email 3521838694@qq.com  && git init


          BUILD_DIR: docs/.vuepress/dist/
          CNAME: www.rayxu6.eu.org